apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-database-scaler.fullname" . }}
  labels:
    {{- include "kubernetes-database-scaler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubernetes-database-scaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubernetes-database-scaler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubernetes-database-scaler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: KUBERNETES_DATABASE_SCALER_DATABASE_DRIVER
            value: {{ .Values.scaler.databaseDriver }}
          - name: KUBERNETES_DATABASE_SCALER_DATABASE_NAME
            value: {{ .Values.scaler.databaseName }}
          - name: KUBERNETES_DATABASE_SCALER_DATABASE_PORT
            value: "{{ .Values.scaler.databasePort }}"
          - name: KUBERNETES_DATABASE_SCALER_DATABASE_HOST
            value: {{ .Values.scaler.databaseHost }}
          - name: KUBERNETES_DATABASE_SCALER_DATABASE_USERNAME
            value: {{ .Values.scaler.databaseUsername }}
          - name: KUBERNETES_DATABASE_SCALER_DATABASE_PASSWORD
            value: {{ .Values.scaler.databasePassword }}
          - name: KUBERNETES_DATABASE_SCALER_DATABASE_USERNAME_FILE
            value: {{ .Values.scaler.databaseUsernameFile }}
          - name: KUBERNETES_DATABASE_SCALER_DATABASE_PASSWORD_FILE
            value: {{ .Values.scaler.databasePasswordFile }}
          - name: KUBERNETES_DATABASE_SCALER_TABLE_NAME
            value: {{ .Values.scaler.tableName }}
          - name: KUBERNETES_DATABASE_SCALER_SQL_CONDITION
            value: {{ .Values.scaler.sqlCondition }}
          - name: KUBERNETES_DATABASE_SCALER_ORIGINAL_DEPLOYMENT_NAMESPACE
            value: {{ .Values.scaler.originalDeploymentNamespace }}
          - name: KUBERNETES_DATABASE_SCALER_ORIGINAL_DEPLOYMENT_NAME
            value: {{ .Values.scaler.originalDeploymentName }}
          - name: KUBERNETES_DATABASE_SCALER_ORIGINAL_VPA_NAME
          - name: KUBERNETES_DATABASE_SCALER_TARGET_DEPLOYMENT_NAME
            value: {{ .Values.scaler.targetDeploymentName }}
          - name: KUBERNETES_DATABASE_SCALER_ENVIRONMENT
            value: {{ .Values.scaler.environment }}
          - name: KUBERNETES_DATABASE_SCALER_EXCLUDE_LABEL
            value: {{ .Values.scaler.excludeLabel }}
          - name: KUBERNETES_DATABASE_SCALER_CHECK_INTERVAL
            value: "{{ .Values.scaler.checkInterval }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 10 }}
      {{- end }}
